### ISSUE TITLE
Getting TypeError: Cannot read property '__schema' of undefined

### ISSUE THREAD

**Issue by schatzdesigns** [prisma/get-graphql-schema#25]
When i try to get the graphql schema from my backend (graphcool), it doesn't work anymore. It worked the first time, but now it no longer works.

What could be the problem?

This is the issue thrown.

`TypeError: Cannot read property '__schema' of undefined
    at Object.buildClientSchema (C:\Users\User\AppData\Roaming\npm\node_modules\get-graphql-schema\node_modules\graphql\utilities\buildClientSchema.js:48:43)
    at C:\Users\User\AppData\Roaming\npm\node_modules\get-graphql-schema\dist\index.js:89:54
    at step (C:\Users\User\AppData\Roaming\npm\node_modules\get-graphql-schema\dist\index.js:33:23)
    at Object.next (C:\Users\User\AppData\Roaming\npm\node_modules\get-graphql-schema\dist\index.js:14:53)
    at fulfilled (C:\Users\User\AppData\Roaming\npm\node_modules\get-graphql-schema\dist\index.js:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)`

**Comment by souenzzo** [comment]
One line reproduce
`npx get-graphql-schema@2.1.2 'https://api.github.com/graphql'`
```
npx: installed 12 in 1.252s
TypeError: Cannot read property '__schema' of undefined
    at Object.buildClientSchema (/home/souenzzo/.npm/_npx/10103/lib/node_modules/get-graphql-schema/node_modules/graphql/utilities/buildClientSchema.js:55:43)
    at /home/souenzzo/.npm/_npx/10103/lib/node_modules/get-graphql-schema/dist/index.js:90:54
    at step (/home/souenzzo/.npm/_npx/10103/lib/node_modules/get-graphql-schema/dist/index.js:33:23)
    at Object.next (/home/souenzzo/.npm/_npx/10103/lib/node_modules/get-graphql-schema/dist/index.js:14:53)
    at fulfilled (/home/souenzzo/.npm/_npx/10103/lib/node_modules/get-graphql-schema/dist/index.js:5:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```
After add the auth token `--header 'Authorization=bearer ....'` worked.. but it can handle a better error message.
